version: "3"
services:
  lfs-server:
    build: .
    ports:
      - 8000:8000
    volumes:
      - "./data:/service/data"
      - "./.ssh:/service/.ssh"
    environment:
      - API_KEY=secure_api_key
      - DATA_FOLDER=/service/data
      - JWT_SECRET=jwt_sercret
      - SSH_PRIVATE_KEY_PATH=/service/.ssh/id_rsa
      - SSH_ENABLED=true
    tty: true
